const root=document.documentElement;const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
const toggle=document.querySelector('.theme-toggle');const stored=localStorage.getItem('portfolio-theme');if(stored==='dark'||stored==='light')root.dataset.theme=stored;else if(window.matchMedia('(prefers-color-scheme: dark)').matches)root.dataset.theme='dark';
function syncThemeLabel(){if(toggle)toggle.setAttribute('aria-label',root.dataset.theme==='dark'?'Switch to light theme':'Switch to dark theme')}syncThemeLabel();toggle?.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('portfolio-theme',root.dataset.theme);syncThemeLabel()});
const navLinks=[...document.querySelectorAll('.header nav a')];const sections=navLinks.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;navLinks.forEach(a=>a.removeAttribute('aria-current'));navLinks.find(a=>a.getAttribute('href')===`#${visible.target.id}`)?.setAttribute('aria-current','page')},{rootMargin:'-25% 0px -60%',threshold:[0,.2,.5]});sections.forEach(s=>observer.observe(s))}
const coverMap=[
['Routledge International Handbook','https://covers.openlibrary.org/b/isbn/9780367539399-L.jpg'],
['Police, Race and Culture','https://books.google.com/books/content?id=iL5EAQAACAAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api'],
['Equality Acts','https://image.thum.io/get/width/500/crop/700/noanimate/https://www.aontas.com/assets/resources/Submissions/Equality%20Acts%20Consultation%20Paper_AONTAS%202021.docx.pdf'],
['National Plan for Equity','https://image.thum.io/get/width/500/crop/700/noanimate/https://www.aontas.com/assets/resources/Submissions/AONTAS%20Submission_NAP%202022-2026.pdf'],
['Educational Equality','https://image.thum.io/get/width/500/crop/700/noanimate/https://www.aontas.com/assets/resources/CEN%20Census/CEN%20Census%20Policy%20Paper.pdf'],
['Lifelong learning','https://image.thum.io/get/width/500/crop/700/noanimate/https://www.ageaction.ie/sites/default/files/attachments/third_and_final_proof.pdf'],
['Value for Money','https://image.thum.io/get/width/500/crop/700/noanimate/http://www.drugsandalcohol.ie/23242/1/ValueforMoneyYouthProjects.pdf']];
for(const link of document.querySelectorAll('.publications>a:not(.publication-feature)')){const title=link.querySelector('strong')?.textContent||'';const found=coverMap.find(([key])=>title.includes(key));if(!found)continue;link.classList.add('publication-with-cover');let img=link.querySelector('.publication-cover');if(!img){img=document.createElement('img');img.className='publication-cover';link.prepend(img)}img.src=found[1];img.alt=`Cover of ${title}`;img.loading='lazy'}