const root=document.documentElement;const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
const toggle=document.querySelector('.theme-toggle');const stored=localStorage.getItem('portfolio-theme');if(stored==='dark'||stored==='light')root.dataset.theme=stored;else if(window.matchMedia('(prefers-color-scheme: dark)').matches)root.dataset.theme='dark';
function syncThemeLabel(){if(toggle)toggle.setAttribute('aria-label',root.dataset.theme==='dark'?'Switch to light theme':'Switch to dark theme')}syncThemeLabel();toggle?.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('portfolio-theme',root.dataset.theme);syncThemeLabel()});
const navLinks=[...document.querySelectorAll('.header nav a')];const sections=navLinks.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;navLinks.forEach(a=>a.removeAttribute('aria-current'));navLinks.find(a=>a.getAttribute('href')===`#${visible.target.id}`)?.setAttribute('aria-current','page')},{rootMargin:'-25% 0px -60%',threshold:[0,.2,.5]});sections.forEach(s=>observer.observe(s))}
const coverMap=[
['Routledge International Handbook','assets/images/routledge-international-handbook-police-ethnography.webp'],
['Police, Race and Culture','assets/images/police-race-culture-new-ireland.webp'],
['Equality Acts','assets/images/aontas-equality-acts-2021.jpeg'],
['National Plan for Equity','assets/images/aontas-equity-access-2022-2026.jpeg'],
['Educational Equality','assets/images/community-education-covid-19.jpeg'],
['Lifelong learning','https://image.thum.io/get/width/500/crop/700/noanimate/https://www.ageaction.ie/sites/default/files/attachments/third_and_final_proof.pdf'],
['Value for Money','assets/images/value-for-money-youth-programmes.jpeg']];
for(const link of document.querySelectorAll('.publications>a:not(.publication-feature)')){const title=link.querySelector('strong')?.textContent||'';const found=coverMap.find(([key])=>title.includes(key));if(!found)continue;link.classList.add('publication-with-cover');let img=link.querySelector('.publication-cover');if(!img){img=document.createElement('img');img.className='publication-cover';link.prepend(img)}img.src=found[1];img.alt=`Cover of ${title}`;img.loading='lazy';img.decoding='async'}
const elderCover=document.querySelector('.publication-feature img');if(elderCover){elderCover.src='assets/images/elder-abuse-context-theory.jpeg';elderCover.alt='Cover of Elder Abuse, Context and Theory: Finland, Ireland, Italy and Romania';elderCover.loading='lazy';elderCover.decoding='async'}
const backToTop=document.querySelector('.back-to-top');if(backToTop){const syncBackToTop=()=>backToTop.classList.toggle('is-visible',window.scrollY>600);syncBackToTop();window.addEventListener('scroll',syncBackToTop,{passive:true})}
